# Television configuration.
#
# Location: ~/.config/television/config.toml
#
# Simon Olofsson <simon@olofsson.de>
#

[shell_integration.keybindings]
command_history = "/"
smart_autocomplete = "ctrl-space"
