default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: fish-syntax
        name: Validate Fish scripts
        entry: fish -n
        language: system
        files: \.fish$
        stages: [pre-push]

      - id: dotbot-config
        name: Validate Dotbot configs
        entry: dotbot -n -c
        language: python
        additional_dependencies: [dotbot]
        files: ^dotbot-.*\.yaml$
        stages: [pre-push]
