# Override for tv zoxide channel.
#
# Simon Olofsson <simon@olofsson.de>
#

[preview]
command = "eza --group-directories-first --all --icons=always --color=always --oneline '{}'"

[keybindings]
enter = "__DELETE__"
