name: Validate

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Validate Fish scripts
        run: |
          sudo apt update
          sudo apt install -y fish
          fish -n fish/**/*.fish

      - name: Validate Dotbot configs
        run: |
          pip install dotbot
          dotbot -n -c dotbot-config.yaml
          dotbot -n -c dotbot-sync.yaml
          dotbot -n -c dotbot-update.yaml
